project_id = "eqrzodfukdnwsogjzmoz"

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.notification-trigger]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.loyalty-service]
verify_jwt = false

[functions.notify-new-order]
verify_jwt = false
